extends Node

const ID = "TeaLovingLad.AAH"

onready var Lure = get_node("/root/SulayreLure")

func _ready():
	Lure.add_content(ID, "axe_cosmetic", "mod://Resources/Cosmetics/axe_cosmetic.tres")
	
	Lure.add_content(ID, "grassblade_cosmetic", "mod://Resources/Cosmetics/grassblade_cosmetic.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Awesome Possum.species_possum", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_possum.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Crystallization.Protogen.species_protogen", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_protogen.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "DarnHyena.YeenFishin.species_hyena", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_hyena.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "GnarlyGnoll.Borzoi.species_borzoi", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_borzoi.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "GnarlyGnoll.Capybara.species_capybara", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_capybara.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "GnarlyGnoll.Deer.species_deer", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_deer.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "HorseMod.species_horse", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_horse.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "otter.species_otter", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_otter.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "RAYTRAC3RCosmetics.species_llama", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_llama.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "RAYTRAC3RCosmetics.species_minty", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_minty.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "RAYTRAC3RCosmetics.species_penguin", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_penguin.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Zea.Species.species_axolotl", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_axolotl.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Zea.Species.species_bat", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_bat.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Zea.Species.species_bear", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_bear.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Zea.Species.species_bird", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_bird_zea.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Zea.Species.species_cube", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_cube.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Zea.Species.species_fennec", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_fennec.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Zea.Species.species_fox", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_fox.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Zea.Species.species_frog", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_frog.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Zea.Species.species_gecko", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_gecko.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Zea.Species.species_goat", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_goat.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Zea.Species.species_leopard", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_leopard.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Zea.Species.species_mouse", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_mouse.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Zea.Species.species_pig", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_pig.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Zea.Species.species_raccoon", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_raccoon.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Zea.Species.species_shark", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_shark.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.grassblade_cosmetic", "Zea.Species.species_sheep", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Grass Blade/grassblade_sheep.tres")
	
	Lure.add_content(ID, "smokingpipe_cosmetic", "mod://Resources/Cosmetics/smokingpipe_cosmetic.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "Awesome Possum.species_possum", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_possum.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "Crystallization.Protogen.species_protogen", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_protogen.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "DarnHyena.YeenFishin.species_hyena", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_hyena.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "GnarlyGnoll.Borzoi.species_borzoi", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_borzoi.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "GnarlyGnoll.Capybara.species_capybara", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_capybara.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "GnarlyGnoll.Deer.species_deer", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_deer.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "HorseMod.species_horse", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_horse.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "Jous.Goats.species_goat", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_goat_jous.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "otter.species_otter", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_otter.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "RAYTRAC3RCosmetics.species_llama", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_llama.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "RAYTRAC3RCosmetics.species_minty", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_dog.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "RAYTRAC3RCosmetics.species_penguin", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_penguin.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "TeaLovingLad.Dracavem.species_dracavem", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_dracavem.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "Zea.Species.species_axolotl", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_axolotl.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "Zea.Species.species_bird", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_bird_zea.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "Zea.Species.species_fennec", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_axolotl.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "Zea.Species.species_fox", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_fox.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "Zea.Species.species_frog", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_frog.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "Zea.Species.species_goat", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_goat_zea.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "Zea.Species.species_leopard", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_leopard.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "Zea.Species.species_mouse", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_mouse.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "Zea.Species.species_pig", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_pig.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "Zea.Species.species_raccoon", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_axolotl.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "Zea.Species.species_shark", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_axolotl.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "Zea.Species.species_sheep", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_sheep.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.smokingpipe_cosmetic", "Zea.Species.species_spider", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Smoking Pipe/smokingpipe_axolotl.tres")
	
	Lure.add_content(ID, "fourleafclover_cosmetic", "mod://Resources/Cosmetics/fourleafclover_cosmetic.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Awesome Possum.species_possum", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_possum.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "DarnHyena.YeenFishin.species_hyena", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_hyena.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "GnarlyGnoll.Borzoi.species_borzoi", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_dog.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "GnarlyGnoll.Capybara.species_capybara", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_capybara.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "HorseMod.species_horse", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_horse.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Jous.Birds.species_bird", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_bird_jous.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Jous.Goats.species_goat", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_goat_jous.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "otter.species_otter", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_otter.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "RAYTRAC3RCosmetics.species_llama", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_llama.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "RAYTRAC3RCosmetics.species_minty", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_minty.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "RAYTRAC3RCosmetics.species_penguin", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_penguin.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "TeaLovingLad.Dracavem.species_dracavem", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_dracavem.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Zea.Species.species_axolotl", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_axolotl.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Zea.Species.species_bat", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_axolotl.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Zea.Species.species_bear", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_bear.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Zea.Species.species_bird", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_bird_zea.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Zea.Species.species_cube", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_cube.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Zea.Species.species_fennec", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_fennec.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Zea.Species.species_fox", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_fox.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Zea.Species.species_frog", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_frog.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Zea.Species.species_gecko", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_gecko.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Zea.Species.species_goat", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_fox.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Zea.Species.species_leopard", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_leopard.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Zea.Species.species_monkey", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_monkey.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Zea.Species.species_raccoon", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_raccoon.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Zea.Species.species_shark", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_shark.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Zea.Species.species_sheep", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_sheep.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.fourleafclover_cosmetic", "Zea.Species.species_spider", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Four-Leaf Clover/fourleafclover_spider.tres")
	
	Lure.add_content(ID, "threeleafclover_cosmetic", "mod://Resources/Cosmetics/threeleafclover_cosmetic.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Awesome Possum.species_possum", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_possum.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "DarnHyena.YeenFishin.species_hyena", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_hyena.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "GnarlyGnoll.Borzoi.species_borzoi", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_dog.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "GnarlyGnoll.Capybara.species_capybara", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_capybara.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "HorseMod.species_horse", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_horse.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Jous.Birds.species_bird", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_bird_jous.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Jous.Goats.species_goat", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_goat_jous.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "otter.species_otter", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_otter.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "RAYTRAC3RCosmetics.species_llama", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_llama.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "RAYTRAC3RCosmetics.species_minty", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_minty.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "RAYTRAC3RCosmetics.species_penguin", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_penguin.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "TeaLovingLad.Dracavem.species_dracavem", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_dracavem.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Zea.Species.species_axolotl", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_axolotl.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Zea.Species.species_bat", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_axolotl.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Zea.Species.species_bear", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_bear.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Zea.Species.species_bird", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_bird_zea.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Zea.Species.species_cube", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_cube.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Zea.Species.species_fennec", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_fennec.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Zea.Species.species_fox", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_fox.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Zea.Species.species_frog", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_frog.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Zea.Species.species_gecko", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_gecko.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Zea.Species.species_goat", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_fox.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Zea.Species.species_leopard", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_leopard.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Zea.Species.species_monkey", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_monkey.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Zea.Species.species_raccoon", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_raccoon.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Zea.Species.species_shark", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_shark.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Zea.Species.species_sheep", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_sheep.tres")
	Lure.assign_cosmetic_mesh(ID, "TeaLovingLad.AAH.threeleafclover_cosmetic", "Zea.Species.species_spider", "res://mods/TeaLovingLad.AAH/Assets/Models/Accessories/Three-Leaf Clover/threeleafclover_spider.tres")
	
	Lure.add_content(ID, "belt_black_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_black_cosmetic.tres")
	Lure.add_content(ID, "belt_black_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_black_thick_cosmetic.tres")
	Lure.add_content(ID, "belt_blue_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_blue_cosmetic.tres")
	Lure.add_content(ID, "belt_blue_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_blue_thick_cosmetic.tres")
	Lure.add_content(ID, "belt_brown_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_brown_cosmetic.tres")
	Lure.add_content(ID, "belt_brown_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_brown_thick_cosmetic.tres")
	Lure.add_content(ID, "belt_green_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_green_cosmetic.tres")
	Lure.add_content(ID, "belt_green_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_green_thick_cosmetic.tres")
	Lure.add_content(ID, "belt_grey_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_grey_cosmetic.tres")
	Lure.add_content(ID, "belt_grey_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_grey_thick_cosmetic.tres")
	Lure.add_content(ID, "belt_maroon_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_maroon_cosmetic.tres")
	Lure.add_content(ID, "belt_maroon_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_maroon_thick_cosmetic.tres")
	Lure.add_content(ID, "belt_midnight_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_midnight_cosmetic.tres")
	Lure.add_content(ID, "belt_midnight_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_midnight_thick_cosmetic.tres")
	Lure.add_content(ID, "belt_olive_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_olive_cosmetic.tres")
	Lure.add_content(ID, "belt_olive_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_olive_thick_cosmetic.tres")
	Lure.add_content(ID, "belt_orange_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_orange_cosmetic.tres")
	Lure.add_content(ID, "belt_orange_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_orange_thick_cosmetic.tres")
	Lure.add_content(ID, "belt_pink_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_pink_cosmetic.tres")
	Lure.add_content(ID, "belt_pink_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_pink_thick_cosmetic.tres")
	Lure.add_content(ID, "belt_purple_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_purple_cosmetic.tres")
	Lure.add_content(ID, "belt_purple_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_purple_thick_cosmetic.tres")
	Lure.add_content(ID, "belt_red_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_red_cosmetic.tres")
	Lure.add_content(ID, "belt_red_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_red_thick_cosmetic.tres")
	Lure.add_content(ID, "belt_salmon_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_salmon_cosmetic.tres")
	Lure.add_content(ID, "belt_salmon_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_salmon_thick_cosmetic.tres")
	Lure.add_content(ID, "belt_stone_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_stone_cosmetic.tres")
	Lure.add_content(ID, "belt_stone_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_stone_thick_cosmetic.tres")
	Lure.add_content(ID, "belt_tan_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_tan_cosmetic.tres")
	Lure.add_content(ID, "belt_tan_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_tan_thick_cosmetic.tres")
	Lure.add_content(ID, "belt_teal_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_teal_cosmetic.tres")
	Lure.add_content(ID, "belt_teal_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_teal_thick_cosmetic.tres")
	Lure.add_content(ID, "belt_white_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_white_cosmetic.tres")
	Lure.add_content(ID, "belt_white_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_white_thick_cosmetic.tres")
	Lure.add_content(ID, "belt_yellow_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_yellow_cosmetic.tres")
	Lure.add_content(ID, "belt_yellow_thick_cosmetic", "mod://Resources/Cosmetics/Coloured/Belts/belt_yellow_thick_cosmetic.tres")
	
	Lure.add_content(ID, "bandana_low_black_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_black_cosmetic.tres")
	Lure.add_content(ID, "bandana_low_blue_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_blue_cosmetic.tres")
	Lure.add_content(ID, "bandana_low_brown_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_brown_cosmetic.tres")
	Lure.add_content(ID, "bandana_low_green_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_green_cosmetic.tres")
	Lure.add_content(ID, "bandana_low_grey_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_grey_cosmetic.tres")
	Lure.add_content(ID, "bandana_low_maroon_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_maroon_cosmetic.tres")
	Lure.add_content(ID, "bandana_low_midnight_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_midnight_cosmetic.tres")
	Lure.add_content(ID, "bandana_low_olive_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_olive_cosmetic.tres")
	Lure.add_content(ID, "bandana_low_orange_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_orange_cosmetic.tres")
	Lure.add_content(ID, "bandana_low_pink_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_pink_cosmetic.tres")
	Lure.add_content(ID, "bandana_low_purple_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_purple_cosmetic.tres")
	Lure.add_content(ID, "bandana_low_red_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_red_cosmetic.tres")
	Lure.add_content(ID, "bandana_low_salmon_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_salmon_cosmetic.tres")
	Lure.add_content(ID, "bandana_low_stone_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_stone_cosmetic.tres")
	Lure.add_content(ID, "bandana_low_tan_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_tan_cosmetic.tres")
	Lure.add_content(ID, "bandana_low_teal_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_teal_cosmetic.tres")
	Lure.add_content(ID, "bandana_low_white_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_white_cosmetic.tres")
	Lure.add_content(ID, "bandana_low_yellow_cosmetic", "mod://Resources/Cosmetics/Coloured/Bandanas Low/bandana_low_yellow_cosmetic.tres")
	
	Lure.add_content(ID, "armwraps_black_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_black_cosmetic.tres")
	Lure.add_content(ID, "armwraps_blue_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_blue_cosmetic.tres")
	Lure.add_content(ID, "armwraps_brown_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_brown_cosmetic.tres")
	Lure.add_content(ID, "armwraps_green_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_green_cosmetic.tres")
	Lure.add_content(ID, "armwraps_grey_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_grey_cosmetic.tres")
	Lure.add_content(ID, "armwraps_maroon_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_maroon_cosmetic.tres")
	Lure.add_content(ID, "armwraps_midnight_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_midnight_cosmetic.tres")
	Lure.add_content(ID, "armwraps_olive_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_olive_cosmetic.tres")
	Lure.add_content(ID, "armwraps_orange_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_orange_cosmetic.tres")
	Lure.add_content(ID, "armwraps_pink_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_pink_cosmetic.tres")
	Lure.add_content(ID, "armwraps_purple_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_purple_cosmetic.tres")
	Lure.add_content(ID, "armwraps_red_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_red_cosmetic.tres")
	Lure.add_content(ID, "armwraps_salmon_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_salmon_cosmetic.tres")
	Lure.add_content(ID, "armwraps_stone_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_stone_cosmetic.tres")
	Lure.add_content(ID, "armwraps_tan_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_tan_cosmetic.tres")
	Lure.add_content(ID, "armwraps_teal_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_teal_cosmetic.tres")
	Lure.add_content(ID, "armwraps_white_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_white_cosmetic.tres")
	Lure.add_content(ID, "armwraps_yellow_cosmetic", "mod://Resources/Cosmetics/Coloured/Arm Wraps/armwraps_yellow_cosmetic.tres")
	
	Lure.add_content(ID, "legwraps_black_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_black_cosmetic.tres")
	Lure.add_content(ID, "legwraps_blue_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_blue_cosmetic.tres")
	Lure.add_content(ID, "legwraps_brown_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_brown_cosmetic.tres")
	Lure.add_content(ID, "legwraps_green_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_green_cosmetic.tres")
	Lure.add_content(ID, "legwraps_grey_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_grey_cosmetic.tres")
	Lure.add_content(ID, "legwraps_maroon_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_maroon_cosmetic.tres")
	Lure.add_content(ID, "legwraps_midnight_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_midnight_cosmetic.tres")
	Lure.add_content(ID, "legwraps_olive_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_olive_cosmetic.tres")
	Lure.add_content(ID, "legwraps_orange_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_orange_cosmetic.tres")
	Lure.add_content(ID, "legwraps_pink_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_pink_cosmetic.tres")
	Lure.add_content(ID, "legwraps_purple_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_purple_cosmetic.tres")
	Lure.add_content(ID, "legwraps_red_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_red_cosmetic.tres")
	Lure.add_content(ID, "legwraps_salmon_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_salmon_cosmetic.tres")
	Lure.add_content(ID, "legwraps_stone_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_stone_cosmetic.tres")
	Lure.add_content(ID, "legwraps_tan_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_tan_cosmetic.tres")
	Lure.add_content(ID, "legwraps_teal_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_teal_cosmetic.tres")
	Lure.add_content(ID, "legwraps_white_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_white_cosmetic.tres")
	Lure.add_content(ID, "legwraps_yellow_cosmetic", "mod://Resources/Cosmetics/Coloured/Leg Wraps/legwraps_yellow_cosmetic.tres")
